/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-03-04 15:25:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1643336605561L));
    _jspx_dependants.put("/WEB-INF/views/main/../common/header.jsp", Long.valueOf(1646361456283L));
    _jspx_dependants.put("jar:file:/C:/WhereWare/WW/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/WhereWare/WW/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/WhereWare/WW/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("    메인화면 \r\n");
      out.write("	http://localhost:8088/mvc/main/main 입력시 이동. 추후 home.jsp 경로로 변경\r\n");
      out.write("	DB가 설정되면 스케줄, 자유게시판, 공지사항, 근태현황 연계\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom fonts for this template-->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link\r\n");
      out.write("        href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template-->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        .profile-nav{\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            font-size: 0.8rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            display: block;\r\n");
      out.write("            padding: 0.5rem;\r\n");
      out.write("            margin: 0 0.5rem;\r\n");
      out.write("            color: #3a3b45;\r\n");
      out.write("            border-radius: 0.35rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-nav:hover {\r\n");
      out.write("            background-color: #eaecf4;\r\n");
      out.write("            color: #3a3b45;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .bg-base-color {background-color: #2A3D72;}\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("	<title>WhereWare</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Page Wrapper -->\r\n");
      out.write("    <div id=\"wrapper\" >\r\n");
      out.write("\r\n");
      out.write("        <!-- Sidebar -->\r\n");
      out.write("        <ul class=\"navbar-nav sidebar bg-base-color sidebar-dark accordion\" id=\"accordionSidebar\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Sidebar - Brand -->\r\n");
      out.write("            <a class=\"sidebar-brand d-flex align-items-center justify-content-center\" href=\"index.html\" >\r\n");
      out.write("                <div class=\"sidebar-brand-icon rotate-n-15\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sidebar-brand-text mx-3\">WhereWare</div>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <hr class=\"sidebar-divider my-0\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Dashboard -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                    <!-- Nav Item - User Information -->\r\n");
      out.write("                <li class=\"nav-item no-arrow\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\" >\r\n");
      out.write("                        <img class=\"rounded-circle\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/undraw_profile.svg\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- Dropdown - User Information -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"py-2 rounded\" style=\"background-color: rgb(200, 204, 255) ;width: 90%; margin: auto;\">\r\n");
      out.write("                        <a class=\"profile-nav\" href=\"login.html\">프로필 관리</a>\r\n");
      out.write("                        <a class=\"profile-nav\" href=\"404.html \" >문서 관리</a>\r\n");
      out.write("                        <a class=\"profile-nav\" href=\"blank.html\" >로그아웃</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </li>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider 매뉴 구분 줄-->\r\n");
      out.write("            <hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#\" data-toggle=\"collapse\" data-target=\"#employeeMeun\" aria-expanded=\"true\"\r\n");
      out.write("                    aria-controls=\"employeeMeun\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-address-card\"></i>\r\n");
      out.write("                    <span>사원 관리</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div id=\"employeeMeun\" class=\"collapse\" aria-labelledby=\"headingPages\"\r\n");
      out.write("                    data-parent=\"#accordionSidebar\">\r\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"\">사원 검색</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"\">사원 수정</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"\">가입 승인</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <!-- Divider 매뉴 구분 줄-->\r\n");
      out.write("            <hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("            <li class=\"nav-item \">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#\" data-toggle=\"collapse\" data-target=\"#documentMenu\" aria-expanded=\"true\"\r\n");
      out.write("                    aria-controls=\"documentMenu\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-folder\"></i>\r\n");
      out.write("                    <span>문서 관리</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                    <div id=\"documentMenu\" class=\"collapse\" aria-labelledby=\"headingPages\"\r\n");
      out.write("                        data-parent=\"#accordionSidebar\">\r\n");
      out.write("                        <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                            <a class=\"collapse-item\" href=\"\">수신 문서</a>\r\n");
      out.write("                            <a class=\"collapse-item\" href=\"\">발신 문서</a>\r\n");
      out.write("                            <a class=\"collapse-item\" href=\"\">문서 검색</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("                        \r\n");
      out.write("            <!-- Divider 매뉴 구분 줄-->\r\n");
      out.write("            <hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#\" data-toggle=\"collapse\" data-target=\"#boardMenu\" aria-expanded=\"true\"\r\n");
      out.write("                    aria-controls=\"boardMenu\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-address-card\"></i>\r\n");
      out.write("                    <span>게시판</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div id=\"boardMenu\" class=\"collapse\" aria-labelledby=\"headingPages\"\r\n");
      out.write("                    data-parent=\"#accordionSidebar\">\r\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/mvc/board/list\">사내 게시판</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("                        \r\n");
      out.write("            <!-- Divider 매뉴 구분 줄-->\r\n");
      out.write("            <hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#\" data-toggle=\"collapse\" data-target=\"#calenderMemu\" aria-expanded=\"true\"\r\n");
      out.write("                    aria-controls=\"calenderMemu\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-address-card\"></i>\r\n");
      out.write("                    <span>일정관리</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div id=\"calenderMemu\" class=\"collapse\" aria-labelledby=\"headingPages\"\r\n");
      out.write("                    data-parent=\"#accordionSidebar\">\r\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/mvc/calendar/calendar\">캘린더</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("                        \r\n");
      out.write("            <!-- Divider 매뉴 구분 줄-->\r\n");
      out.write("            <hr class=\"sidebar-divider\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Pages Collapse Menu -->\r\n");
      out.write("            <li class=\"nav-item \">\r\n");
      out.write("                <a class=\"nav-link\" href=\"#\" data-toggle=\"collapse\" data-target=\"#cmtMenu\" aria-expanded=\"true\"\r\n");
      out.write("                    aria-controls=\"cmtMenu\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-address-card\"></i>\r\n");
      out.write("                    <span>근태 관리</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div id=\"cmtMenu\" class=\"collapse\" aria-labelledby=\"headingPages\"\r\n");
      out.write("                    data-parent=\"#accordionSidebar\">\r\n");
      out.write("                    <div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/mvc/cmt/dashBoard\">근태 확인</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/mvc/cmt/modify\">근태 수정</a>\r\n");
      out.write("                        <a class=\"collapse-item\" href=\"/mvc/cmt/monthly\">월별 근태</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Charts -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"charts.html\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-address-book\"></i>\r\n");
      out.write("                    <span>사원 검색</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Nav Item - Tables -->\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"tables.html\">\r\n");
      out.write("                    <i class=\"fas fa-fw fa-table\"></i>\r\n");
      out.write("                    <span>Tables</span></a>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <!-- Divider -->\r\n");
      out.write("            <hr class=\"sidebar-divider d-none d-md-block\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Sidebar Toggler (Sidebar) -->\r\n");
      out.write("            <div class=\"text-center d-none d-md-inline\">\r\n");
      out.write("                <button class=\"rounded-circle border-0\" id=\"sidebarToggle\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("        <!-- End of Sidebar -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Content Wrapper -->\r\n");
      out.write("        <div id=\"content-wrapper\" class=\"d-flex flex-column\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Main Content -->\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Topbar -->\r\n");
      out.write("                <nav class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- Sidebar Toggle (Topbar) -->\r\n");
      out.write("                    <button id=\"sidebarToggleTop\" class=\"btn btn-link d-md-none rounded-circle mr-3\">\r\n");
      out.write("                        <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- Topbar Navbar -->\r\n");
      out.write("                    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\r\n");
      out.write("                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->\r\n");
      out.write("                        <li class=\"nav-item dropdown no-arrow d-sm-none\">\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"searchDropdown\" role=\"button\"\r\n");
      out.write("                                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"fas fa-search fa-fw\"></i>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <!-- Dropdown - Messages -->\r\n");
      out.write("                            <div class=\"dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in\"\r\n");
      out.write("                                aria-labelledby=\"searchDropdown\">\r\n");
      out.write("                                <form class=\"form-inline mr-auto w-100 navbar-search\">\r\n");
      out.write("                                    <div class=\"input-group\">\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control bg-light border-0 small\"\r\n");
      out.write("                                            placeholder=\"Search for...\" aria-label=\"Search\"\r\n");
      out.write("                                            aria-describedby=\"basic-addon2\">\r\n");
      out.write("                                        <div class=\"input-group-append\">\r\n");
      out.write("                                            <button class=\"btn btn-primary\" type=\"button\">\r\n");
      out.write("                                                <i class=\"fas fa-search fa-sm\"></i>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Nav Item - Alerts -->\r\n");
      out.write("                        <li class=\"nav-item dropdown no-arrow mx-1\">\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\" role=\"button\"\r\n");
      out.write("                                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"fas fa-bell fa-fw\"></i>\r\n");
      out.write("                                <!-- Counter - Alerts -->\r\n");
      out.write("                                <span class=\"badge badge-danger badge-counter\">3+</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <!-- Dropdown - Alerts -->\r\n");
      out.write("                            <div class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("                                aria-labelledby=\"alertsDropdown\">\r\n");
      out.write("                                <h6 class=\"dropdown-header\">\r\n");
      out.write("                                    Alerts Center\r\n");
      out.write("                                </h6>\r\n");
      out.write("                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("                                    <div class=\"mr-3\">\r\n");
      out.write("                                        <div class=\"icon-circle bg-primary\">\r\n");
      out.write("                                            <i class=\"fas fa-file-alt text-white\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <div class=\"small text-gray-500\">December 12, 2019</div>\r\n");
      out.write("                                        <span class=\"font-weight-bold\">A new monthly report is ready to download!</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("                                    <div class=\"mr-3\">\r\n");
      out.write("                                        <div class=\"icon-circle bg-success\">\r\n");
      out.write("                                            <i class=\"fas fa-donate text-white\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <div class=\"small text-gray-500\">December 7, 2019</div>\r\n");
      out.write("                                        $290.29 has been deposited into your account!\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("                                    <div class=\"mr-3\">\r\n");
      out.write("                                        <div class=\"icon-circle bg-warning\">\r\n");
      out.write("                                            <i class=\"fas fa-exclamation-triangle text-white\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <div class=\"small text-gray-500\">December 2, 2019</div>\r\n");
      out.write("                                        Spending Alert: We've noticed unusually high spending for your account.\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Show All Alerts</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Nav Item - Messages -->\r\n");
      out.write("                        <li class=\"nav-item dropdown no-arrow mx-1\">\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"messagesDropdown\" role=\"button\"\r\n");
      out.write("                                data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"fas fa-envelope fa-fw\"></i>\r\n");
      out.write("                                <!-- Counter - Messages -->\r\n");
      out.write("                                <span class=\"badge badge-danger badge-counter\">7</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <!-- Dropdown - Messages -->\r\n");
      out.write("                            <div class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\"\r\n");
      out.write("                                aria-labelledby=\"messagesDropdown\">\r\n");
      out.write("                                <h6 class=\"dropdown-header\">\r\n");
      out.write("                                    Message Center\r\n");
      out.write("                                </h6>\r\n");
      out.write("                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("                                    <div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("                                        <img class=\"rounded-circle\" src=\"img/undraw_profile_1.svg\"\r\n");
      out.write("                                            alt=\"...\">\r\n");
      out.write("                                        <div class=\"status-indicator bg-success\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"font-weight-bold\">\r\n");
      out.write("                                        <div class=\"text-truncate\">Hi there! I am wondering if you can help me with a\r\n");
      out.write("                                            problem I've been having.</div>\r\n");
      out.write("                                        <div class=\"small text-gray-500\">Emily Fowler · 58m</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("                                    <div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("                                        <img class=\"rounded-circle\" src=\"img/undraw_profile_2.svg\"\r\n");
      out.write("                                            alt=\"...\">\r\n");
      out.write("                                        <div class=\"status-indicator\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <div class=\"text-truncate\">I have the photos that you ordered last month, how\r\n");
      out.write("                                            would you like them sent to you?</div>\r\n");
      out.write("                                        <div class=\"small text-gray-500\">Jae Chun · 1d</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("                                    <div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("                                        <img class=\"rounded-circle\" src=\"img/undraw_profile_3.svg\"\r\n");
      out.write("                                            alt=\"...\">\r\n");
      out.write("                                        <div class=\"status-indicator bg-warning\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <div class=\"text-truncate\">Last month's report looks great, I am very happy with\r\n");
      out.write("                                            the progress so far, keep up the good work!</div>\r\n");
      out.write("                                        <div class=\"small text-gray-500\">Morgan Alvarez · 2d</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"dropdown-item d-flex align-items-center\" href=\"#\">\r\n");
      out.write("                                    <div class=\"dropdown-list-image mr-3\">\r\n");
      out.write("                                        <img class=\"rounded-circle\" src=\"https://source.unsplash.com/Mv9hjnEUHR4/60x60\"\r\n");
      out.write("                                            alt=\"...\">\r\n");
      out.write("                                        <div class=\"status-indicator bg-success\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <div class=\"text-truncate\">Am I a good boy? The reason I ask is because someone\r\n");
      out.write("                                            told me that people say this to all dogs, even if they aren't good...</div>\r\n");
      out.write("                                        <div class=\"small text-gray-500\">Chicken the Dog · 2w</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Read More Messages</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"topbar-divider d-none d-sm-block\"></div>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- End of Topbar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        ul{\r\n");
      out.write("            list-style: none;\r\n");
      out.write("        }\r\n");
      out.write("        li{\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .tab{\r\n");
      out.write("            margin-left: 30px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .div1{\r\n");
      out.write("            /* 움직이는 시간이 위치하는 div */\r\n");
      out.write("            height: 90px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .time{\r\n");
      out.write("            /* 움직이는 시간 숫자 */\r\n");
      out.write("        display: inline;\r\n");
      out.write("        margin-left: 50%;\r\n");
      out.write("        color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .progress-bar {\r\n");
      out.write("            /* 움직이는 시간 */\r\n");
      out.write("        width: 240px;\r\n");
      out.write("        height: 30px;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        bottom: 0;\r\n");
      out.write("        z-index: 9;\r\n");
      out.write("        transition: var(--transition);\r\n");
      out.write("        }\r\n");
      out.write("        #progress{\r\n");
      out.write("            background-color: cornflowerblue;\r\n");
      out.write("        }\r\n");
      out.write("        #progress2{\r\n");
      out.write("            background-color: steelblue;\r\n");
      out.write("        }\r\n");
      out.write("        #progress3{\r\n");
      out.write("            background-color: #2A3D72;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .div2{\r\n");
      out.write("            /* 시간 밑 배경을 약간 회색으로 보이게하는  나머지 div 전부 포함되어있음  */\r\n");
      out.write("            background-color: #f1f4f7;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            display: block;\r\n");
      out.write("            overflow: inherit;\r\n");
      out.write("        }\r\n");
      out.write("            .div3{\r\n");
      out.write("                /* 달력이 위차하는 div */\r\n");
      out.write("                width: 400px;\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                margin-left: 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            #calendar {\r\n");
      out.write("                border-collapse:collapse;\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("            #th1 {\r\n");
      out.write("                height: 30px;\r\n");
      out.write("                width: 200px;\r\n");
      out.write("                background-color:  #2A3D72;\r\n");
      out.write("                font-size: 10px;\r\n");
      out.write("                border-top:  0.5px solid black;\r\n");
      out.write("                border-right:  0.5px solid black;\r\n");
      out.write("                color: white;\r\n");
      out.write("            }\r\n");
      out.write("            .date {\r\n");
      out.write("                text-align: center;\r\n");
      out.write("                height: 20px;\r\n");
      out.write("                border: 0.5px solid black;\r\n");
      out.write("                font-size: 10px;\r\n");
      out.write("                font-weight: 700;\r\n");
      out.write("                background-color: white;\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("            input {\r\n");
      out.write("                height: 20px;\r\n");
      out.write("                width: 20px;\r\n");
      out.write("                border: none;\r\n");
      out.write("                background-color:  #2A3D72;\r\n");
      out.write("                font-size: 20px;\r\n");
      out.write("                cursor: pointer;\r\n");
      out.write("            }\r\n");
      out.write("            .year_mon{\r\n");
      out.write("                font-size: 10px;\r\n");
      out.write("            }\r\n");
      out.write("            .colToday{\r\n");
      out.write("                background-color: rgb(255, 250, 223);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("                .div4{\r\n");
      out.write("                    /* 스케줄 div */\r\n");
      out.write("                    height: 200px;\r\n");
      out.write("                    width: 800px;\r\n");
      out.write("                    display: inline-block;\r\n");
      out.write("                    margin-left: 100px;\r\n");
      out.write("                }\r\n");
      out.write("                .tab2{\r\n");
      out.write("                    border: 1px solid #2A3D72 ;\r\n");
      out.write("                }\r\n");
      out.write("                .th2{\r\n");
      out.write("                    background-color: white;\r\n");
      out.write("                    \r\n");
      out.write("                    width: 400px;\r\n");
      out.write("                }\r\n");
      out.write("                .td2{\r\n");
      out.write("                    background-color: white;\r\n");
      out.write("                    border-right: black solid 0.5px;\r\n");
      out.write("                    height: 150px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .td3{\r\n");
      out.write("                    background-color: white;\r\n");
      out.write("                    height: 30px;\r\n");
      out.write("                    \r\n");
      out.write("                }\r\n");
      out.write("                table{\r\n");
      out.write("                    border-collapse:collapse;\r\n");
      out.write("                }\r\n");
      out.write("                .tab3{\r\n");
      out.write("                    border: 0.5px solid #2A3D72 ;\r\n");
      out.write("                    \r\n");
      out.write("                }\r\n");
      out.write("                tr{\r\n");
      out.write("                    border: 0.5px solid gray;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("            .div5{\r\n");
      out.write("                /* 자유게시판 div */\r\n");
      out.write("                width: 800px;\r\n");
      out.write("                margin-left: 10px;\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                margin-top: 100px;\r\n");
      out.write("            }\r\n");
      out.write("            .div6{\r\n");
      out.write("                /* 공지사항 div */\r\n");
      out.write("                width: 400px;\r\n");
      out.write("                height: 300px;\r\n");
      out.write("                display: inline-table;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                margin-top: 100px;\r\n");
      out.write("                margin-left: 50px;\r\n");
      out.write("            }\r\n");
      out.write("            .notice{\r\n");
      out.write("                width: 400px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .div7{\r\n");
      out.write("                /* 공지사항 div */\r\n");
      out.write("                width: 400px;\r\n");
      out.write("                background-color: white;\r\n");
      out.write("            }\r\n");
      out.write("            .th3{\r\n");
      out.write("                height: 20px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("                .attend{\r\n");
      out.write("                    width: 400px;\r\n");
      out.write("                }\r\n");
      out.write("                .attend1{\r\n");
      out.write("                    width: 60px;\r\n");
      out.write("                    height: 60px;\r\n");
      out.write("                    display: inline-block;\r\n");
      out.write("                    background-color: #D3D3D3;\r\n");
      out.write("                    border-radius: 70%;\r\n");
      out.write("                    text-align: center;\r\n");
      out.write("                    line-height: 6;\r\n");
      out.write("                    margin-left: 35px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("    <script src=\"/jquery-3.6.0.js\"></script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        // 달력 스크립트\r\n");
      out.write("        $(function(){\r\n");
      out.write("    var today = new Date();\r\n");
      out.write("    var date = new Date();           \r\n");
      out.write("\r\n");
      out.write("    $(\"input[name=preMon]\").click(function() { // 이전달\r\n");
      out.write("        $(\"#calendar > tbody > td\").remove();\r\n");
      out.write("        $(\"#calendar > tbody > tr\").remove();\r\n");
      out.write("        today = new Date ( today.getFullYear(), today.getMonth()-1, today.getDate());\r\n");
      out.write("        buildCalendar();\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("    $(\"input[name=nextMon]\").click(function(){ //다음달\r\n");
      out.write("        $(\"#calendar > tbody > td\").remove();\r\n");
      out.write("        $(\"#calendar > tbody > tr\").remove();\r\n");
      out.write("        today = new Date ( today.getFullYear(), today.getMonth()+1, today.getDate());\r\n");
      out.write("        buildCalendar();\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function buildCalendar() {\r\n");
      out.write("        \r\n");
      out.write("        nowYear = today.getFullYear();\r\n");
      out.write("        nowMonth = today.getMonth();\r\n");
      out.write("        firstDate = new Date(nowYear,nowMonth,1).getDate();\r\n");
      out.write("        firstDay = new Date(nowYear,nowMonth,1).getDay(); //1st의 요일\r\n");
      out.write("        lastDate = new Date(nowYear,nowMonth+1,0).getDate();\r\n");
      out.write("\r\n");
      out.write("        if((nowYear%4===0 && nowYear % 100 !==0) || nowYear%400===0) { //윤년 적용\r\n");
      out.write("            lastDate[1]=29;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(\".year_mon\").text(nowYear+\"년 \"+(nowMonth+1)+\"월\");\r\n");
      out.write("\r\n");
      out.write("        for (i=0; i<firstDay; i++) { //첫번째 줄 빈칸\r\n");
      out.write("            $(\"#calendar tbody:last\").append(\"<td></td>\");\r\n");
      out.write("        }\r\n");
      out.write("        for (i=1; i <=lastDate; i++){ // 날짜 채우기\r\n");
      out.write("            plusDate = new Date(nowYear,nowMonth,i).getDay();\r\n");
      out.write("            if (plusDate==0) {\r\n");
      out.write("                $(\"#calendar tbody:last\").append(\"<tr></tr>\");\r\n");
      out.write("            }\r\n");
      out.write("            $(\"#calendar tbody:last\").append(\"<td class='date'>\"+ i +\"</td>\");\r\n");
      out.write("        }\r\n");
      out.write("        if($(\"#calendar > tbody > td\").length%7!=0) { //마지막 줄 빈칸\r\n");
      out.write("            for(i=1; i<= $(\"#calendar > tbody > td\").length%7; i++) {\r\n");
      out.write("                $(\"#calendar tbody:last\").append(\"<td></td>\");\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        $(\".date\").each(function(index){ // 오늘 날짜 표시\r\n");
      out.write("            if(nowYear==date.getFullYear() && nowMonth==date.getMonth() && $(\".date\").eq(index).text()==date.getDate()) {\r\n");
      out.write("                $(\".date\").eq(index).addClass('colToday');\r\n");
      out.write("            }\r\n");
      out.write("        }) \r\n");
      out.write("    }\r\n");
      out.write("    buildCalendar();\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"div1\">\r\n");
      out.write("        <div class=\"bottom\">\r\n");
      out.write("                <div class=\"progress-bar\" id=\"progress3\">\r\n");
      out.write("                    <p id='hour' class=\"time\"> 00 </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"bottom\">\r\n");
      out.write("                <div class=\"progress-bar\" id=\"progress2\">\r\n");
      out.write("                        <p id='minute'  class=\"time\"> 00 </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"bottom\">\r\n");
      out.write("                <div class=\"progress-bar\" id=\"progress\">\r\n");
      out.write("                        <p id='second'  class=\"time\"> 00 </p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"div2\">\r\n");
      out.write("        <div class=\"div3\">\r\n");
      out.write("            <div>\r\n");
      out.write("                달력\r\n");
      out.write("            </div>\r\n");
      out.write("            <table id=\"calendar\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th id=\"th1\"><input name=\"preMon\" type=\"button\" value=\"<\"></th>\r\n");
      out.write("                        <th id=\"th1\" colspan=\"5\" class=\"year_mon\"></th>\r\n");
      out.write("                        <th id=\"th1\"><input name=\"nextMon\" type=\"button\" value=\">\"></th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th id=\"th1\">Sun</th>\r\n");
      out.write("                        <th id=\"th1\">Mon</th>\r\n");
      out.write("                        <th id=\"th1\">Tue</th>\r\n");
      out.write("                        <th id=\"th1\">Wed</th>\r\n");
      out.write("                        <th id=\"th1\">Thu</th>\r\n");
      out.write("                        <th id=\"th1\">Fri</th>\r\n");
      out.write("                        <th id=\"th1\">Sat</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"div4\">\r\n");
      out.write("            <div>\r\n");
      out.write("                스케줄\r\n");
      out.write("            </div>\r\n");
      out.write("            <table class=\"tab2\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th class=\"th2\">Sun</th>\r\n");
      out.write("                    <th class=\"th2\">Mon</th>\r\n");
      out.write("                    <th class=\"th2\">Tue</th>\r\n");
      out.write("                    <th class=\"th2\">Wed</th>\r\n");
      out.write("                    <th class=\"th2\">Thu</th>\r\n");
      out.write("                    <th class=\"th2\">Fri</th>\r\n");
      out.write("                    <th class=\"th2\">Sat</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td class=\"td2\"></td>\r\n");
      out.write("                    <td class=\"td2\"></td>\r\n");
      out.write("                    <td class=\"td2\"></td>\r\n");
      out.write("                    <td class=\"td2\"></td>\r\n");
      out.write("                    <td class=\"td2\"></td>\r\n");
      out.write("                    <td class=\"td2\"></td>\r\n");
      out.write("                    <td class=\"td2\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"div5\">\r\n");
      out.write("            <div>\r\n");
      out.write("                자유게시판\r\n");
      out.write("            </div>\r\n");
      out.write("            <table class=\"tab3\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th class=\"th2\">제목</th>\r\n");
      out.write("                    <th class=\"th2\">작성자</th>\r\n");
      out.write("                    <th class=\"th2\">등록일</th>\r\n");
      out.write("                    <th class=\"th2\">조회수</th>\r\n");
      out.write("                    <th class=\"th2\">카테고리</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                    <td class=\"td3\"></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"div6\">\r\n");
      out.write("            <div class=\"notice\">공지사항</div>\r\n");
      out.write("            <div >\r\n");
      out.write("                <table class=\"div7\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"th3\"></th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"th3\"></th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"th3\"></th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"th3\"></th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"th3\"></th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"attend\">근태현황</div>\r\n");
      out.write("            <div class=\"attend1\">근무</div>\r\n");
      out.write("            <div class=\"attend1\">야근</div>\r\n");
      out.write("            <div class=\"attend1\">지각</div>\r\n");
      out.write("            <div class=\"attend1\">반차</div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        // 움직이는 시간 스크립트\r\n");
      out.write("    const hour = document.getElementById('hour');\r\n");
      out.write("const minute = document.getElementById('minute');\r\n");
      out.write("const second = document.getElementById('second');\r\n");
      out.write("const progress = document.getElementById('progress');\r\n");
      out.write("const progress2 = document.getElementById('progress2');\r\n");
      out.write("const progress3 = document.getElementById('progress3');\r\n");
      out.write("function showCurrentTime() {\r\n");
      out.write("    let date = new Date();\r\n");
      out.write("    let hr = date.getHours();\r\n");
      out.write("    let min = date.getMinutes();\r\n");
      out.write("    let sec = date.getSeconds();\r\n");
      out.write("    hour.textContent = hr;\r\n");
      out.write("    minute.textContent = min;\r\n");
      out.write("    second.textContent = sec;\r\n");
      out.write("    progress.style.width = (sec / 60) * 100 + '%'\r\n");
      out.write("    progress2.style.width = (min / 60) * 100 + '%'\r\n");
      out.write("    progress3.style.width = (hr / 24) * 100 + '%'\r\n");
      out.write("}\r\n");
      out.write("setInterval(showCurrentTime, 1000)\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/main/main.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/main/main.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main/main.jsp(6,0) '${ pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/main/../common/header.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("path");
      // /WEB-INF/views/main/../common/header.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main/../common/header.jsp(5,0) '${ pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
